# Generated by Django 6.0.5 on 2026-05-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
