# Generated by Django 6.0.5 on 2026-05-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quarto',
            name='tipo',
            field=models.CharField(default='Solteiro', max_length=30),
            preserve_default=False,
        ),
    ]
