# Generated by Django 6.0.5 on 2026-06-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0002_quarto_disponivel_quarto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='capacidade',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quarto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='tipo',
            field=models.CharField(choices=[('Solteiro', 'Solteiro'), ('Casal', 'Casal'), ('Luxo', 'Luxo'), ('Família', 'Família')], max_length=20),
        ),
    ]
