# Generated by Django 6.0.5 on 2026-06-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('Reservada', 'Reservada'), ('Hospedada', 'Hospedada'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], max_length=20),
        ),
    ]
